Repository cse110-sp24-group8/cse110-sp24-group8, pull requests merged in 2024-06, with the labels that each got.

#96 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE /pull_request_template.md
Labels: documentation

#95 Documentation - Padding at the bottom of the box
  src/scripts/main/public/styles/documentation.css
Labels: documentation, css

#93 Added Delete Button, saving to Local Storage, and JSDocs
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/js/feedback.js
  src/scripts/main/public/styles/feedback.css
Labels: js, page interaction

#91 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation

#90 Added rename file feature as a button
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/js/documentation.js
  src/scripts/main/public/styles/documentation.css
Labels: enhancement, html, css, js

#100 TaskList - totalTasks, completedTasks
  src/scripts/main/public/js/task_script.js
Labels: js, page interaction

#105 Fixed template organization in repository
  .github/bug-report.md
  .github/pull_request_template.md
  .github/workflows/issus-templates.md
  .github/workflows/pullrequest-template.md
  src/scripts/main/public/styles/markdown.css
Labels: bug

#98 Merge Code-Log-Js to main
  src/scripts/main/public/html/code-log.html
  src/scripts/main/public/js/code-log.js
  src/scripts/main/public/styles/code-log.css
  src/scripts/main/public/styles/feedback.css
  src/scripts/main/public/styles/main.css
  src/scripts/main/public/styles/markdown.css
Labels: enhancement, html, css, js

#114 Sprint review retro
  admin/meetings/042824-restrospective-warmup.md
  admin/meetings/052224-Sprint-1-review.md
  admin/meetings/052224-restrospective-1.md
  admin/meetings/060424-Sprint-2-review.md
  admin/meetings/060424-restrospective-2.md
Labels: documentation

#107 Added E2E testing setup
  .github/workflows/main.yml
  __tests__/e2e.test.js
  jest-puppeteer.config.cjs
  live-server.js
  package-lock.json
  package.json
Labels: testing

#115 Calendar JS Functionality
  src/scripts/main/public/html/addEvent.html
  src/scripts/main/public/html/editEvent.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/js/task_script.js
  src/scripts/main/public/js/team_calendar.js
  src/scripts/main/public/styles/team_calendar.css
Labels: bug, js

#113 Finished README section (Apart from CI/CD and Demo Video)
  README.md
Labels: documentation

#112 documentation-page enhancements
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/js/documentation.js
  src/scripts/main/public/styles/documentation.css
  src/scripts/main/public/styles/markdown.css
Labels: bug, documentation, html, css

#102 fixed the hitbox for the add button on the Feedback page
  src/scripts/main/public/html/feedback.html
Labels: html, page interaction

#121 Update README.md | Fixed Grammar and misspelled words
  README.md
Labels: documentation

#128 Event parse code update
  src/scripts/main/public/html/addlist.html
  src/scripts/main/public/html/editEvent.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/index.html
  src/scripts/main/public/js/dashboard.js
  src/scripts/main/public/js/task_script.js
  src/scripts/main/public/js/team_calendar.js
  src/scripts/main/public/styles/code-log.css
  src/scripts/main/public/styles/dashboard.css
  src/scripts/main/public/styles/main.css
  src/scripts/main/public/styles/task-list.css
  src/scripts/main/public/styles/team_calendar.css
Labels: css, js, dashboard

#132 Workflow fix
  .github/workflows/main.yml
Labels: bug

#136 Few bugs fixed
  admin/branding/images/LeCoders_Logo.png
  src/scripts/main/public/html/code-log.html
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/html/sidebar.html
  src/scripts/main/public/html/task-list.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/index.html
  src/scripts/main/public/js/task_script.js
  src/scripts/main/public/js/team_calendar.js
  src/scripts/main/public/styles/code-log.css
  src/scripts/main/public/styles/dashboard.css
  src/scripts/main/public/styles/documentation.css
  src/scripts/main/public/styles/feedback.css
  src/scripts/main/public/styles/main.css
  src/scripts/main/public/styles/task-list.css
  src/scripts/main/public/styles/team_calendar.css
Labels: bug, css, js

#139 Sprint Video 2 and Meeting notes
  admin/meetings/060724-featureWrapUp.md
  admin/videos/statusvideo2.md
Labels: documentation

#145 added noscript
  src/scripts/main/public/html/code-log.html
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/html/task-list.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/img/No_Script_Background.png
  src/scripts/main/public/index.html
  src/scripts/main/public/styles/main.css
Labels: html, css

#147 add debugging statements to figure out if ci environment differrent f…
  .github/workflows/main.yml
Labels: testing

#148 get rid of debugging lines
  .github/workflows/main.yml
Labels: testing

#149 Got rid of comment that broke workflow
  .github/workflows/main.yml
Labels: testing

#141 Fixed minor bugs on the Calendar page.
  src/scripts/main/public/js/team_calendar.js
  src/scripts/main/public/styles/team_calendar.css
Labels: bug, css, page interaction

#150 Hamburger button
  src/scripts/main/public/html/code-log.html
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/html/task-list.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/icons/calendar-icon-black.png
  src/scripts/main/public/icons/calendar-icon-grey.png
  src/scripts/main/public/icons/calendar-icon-purple.png
  src/scripts/main/public/icons/calendar-icon-red.png
  src/scripts/main/public/icons/calendar-icon-white.png
  src/scripts/main/public/icons/calendar-icon-yellow.png
  src/scripts/main/public/icons/codelog-icon-black.png
  src/scripts/main/public/icons/codelog-icon-grey.png
  src/scripts/main/public/icons/codelog-icon-purple.png
  src/scripts/main/public/icons/codelog-icon-red.png
  src/scripts/main/public/icons/codelog-icon-white.png
  src/scripts/main/public/icons/codelog-icon-yellow.png
  src/scripts/main/public/icons/dashboard-icon-black.png
  src/scripts/main/public/icons/dashboard-icon-grey.png
  src/scripts/main/public/icons/dashboard-icon-purple.png
  src/scripts/main/public/icons/dashboard-icon-red.png
  src/scripts/main/public/icons/dashboard-icon-white.png
  src/scripts/main/public/icons/dashboard-icon-yellow.png
  src/scripts/main/public/icons/documentation-icon-black.png
  src/scripts/main/public/icons/documentation-icon-grey.png
  src/scripts/main/public/icons/documentation-icon-purple.png
  src/scripts/main/public/icons/documentation-icon-red.png
  src/scripts/main/public/icons/documentation-icon-white.png
  src/scripts/main/public/icons/documentation-icon-yellow.png
  src/scripts/main/public/icons/feedback-icon-black.png
  src/scripts/main/public/icons/feedback-icon-grey.png
  src/scripts/main/public/icons/feedback-icon-purple.png
  src/scripts/main/public/icons/feedback-icon-red.png
  src/scripts/main/public/icons/feedback-icon-white.png
  src/scripts/main/public/icons/feedback-icon-yellow.png
  src/scripts/main/public/icons/tasklist-icon-black.png
  src/scripts/main/public/icons/tasklist-icon-grey.png
  src/scripts/main/public/icons/tasklist-icon-purple.png
  src/scripts/main/public/icons/tasklist-icon-red.png
  src/scripts/main/public/icons/tasklist-icon-white.png
  src/scripts/main/public/icons/tasklist-icon-yellow.png
  src/scripts/main/public/index.html
  src/scripts/main/public/js/loadNav.js
  src/scripts/main/public/js/themeswitch.js
  src/scripts/main/public/styles/main.css
Labels: sidebar

#138 Theme switcher
  src/scripts/main/public/html/code-log.html
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/html/task-list.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/icons/calendar-icon-black.png
  src/scripts/main/public/icons/calendar-icon-grey.png
  src/scripts/main/public/icons/calendar-icon-purple.png
  src/scripts/main/public/icons/calendar-icon-red.png
  src/scripts/main/public/icons/calendar-icon-white.png
  src/scripts/main/public/icons/calendar-icon-yellow.png
  src/scripts/main/public/icons/codelog-icon-black.png
  src/scripts/main/public/icons/codelog-icon-grey.png
  src/scripts/main/public/icons/codelog-icon-purple.png
  src/scripts/main/public/icons/codelog-icon-red.png
  src/scripts/main/public/icons/codelog-icon-white.png
  src/scripts/main/public/icons/codelog-icon-yellow.png
  src/scripts/main/public/icons/dashboard-icon-black.png
  src/scripts/main/public/icons/dashboard-icon-grey.png
  src/scripts/main/public/icons/dashboard-icon-purple.png
  src/scripts/main/public/icons/dashboard-icon-red.png
  src/scripts/main/public/icons/dashboard-icon-white.png
  src/scripts/main/public/icons/dashboard-icon-yellow.png
  src/scripts/main/public/icons/documentation-icon-black.png
  src/scripts/main/public/icons/documentation-icon-grey.png
  src/scripts/main/public/icons/documentation-icon-purple.png
  src/scripts/main/public/icons/documentation-icon-red.png
  src/scripts/main/public/icons/documentation-icon-white.png
  src/scripts/main/public/icons/documentation-icon-yellow.png
  src/scripts/main/public/icons/feedback-icon-black.png
  src/scripts/main/public/icons/feedback-icon-grey.png
  src/scripts/main/public/icons/feedback-icon-purple.png
  src/scripts/main/public/icons/feedback-icon-red.png
  src/scripts/main/public/icons/feedback-icon-white.png
  src/scripts/main/public/icons/feedback-icon-yellow.png
  src/scripts/main/public/icons/tasklist-icon-black.png
  src/scripts/main/public/icons/tasklist-icon-grey.png
  src/scripts/main/public/icons/tasklist-icon-purple.png
  src/scripts/main/public/icons/tasklist-icon-red.png
  src/scripts/main/public/icons/tasklist-icon-white.png
  src/scripts/main/public/icons/tasklist-icon-yellow.png
  src/scripts/main/public/img/No_Script_Background.png
  src/scripts/main/public/index.html
  src/scripts/main/public/js/dashboard.js
  src/scripts/main/public/js/loadNav.js
  src/scripts/main/public/js/themeswitch.js
  src/scripts/main/public/styles/code-log.css
  src/scripts/main/public/styles/dashboard.css
  src/scripts/main/public/styles/documentation.css
  src/scripts/main/public/styles/feedback.css
  src/scripts/main/public/styles/main.css
  src/scripts/main/public/styles/task-list.css
  src/scripts/main/public/styles/team_calendar.css
  src/scripts/main/public/styles/var.css
Labels: enhancement, html, css, js, page interaction

#137 fixed mobile view and enhanced js func
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/js/documentation.js
  src/scripts/main/public/styles/documentation.css
Labels: bug, html, css, js

#155 Fixed pathing for all the sidebar icons
  src/scripts/main/public/html/code-log.html
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/html/sidebar.html
  src/scripts/main/public/html/task-list.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/index.html
  src/scripts/main/public/js/code-log.js
  src/scripts/main/public/js/loadNav.js
  src/scripts/main/public/js/themeswitch.js
  src/scripts/main/public/styles/code-log.css
  src/scripts/main/public/styles/documentation.css
  src/scripts/main/public/styles/main.css
  src/scripts/main/public/styles/team_calendar.css
Labels: sidebar

#153 Unit test Fix
  .github/workflows/main.yml
  __tests__/e2e/e2e.test.js
  __tests__/unit/dashboard.test.js
  __tests__/unit/documentation.test.js
  __tests__/unit/feedback.test.js
  __tests__/unit/subtract.test.js
  __tests__/unit/team_calendar.test.js
  package-lock.json
  package.json
  src/scripts/main/public/html/feedback.html
  src/scripts/main/public/html/team_calendar.html
  src/scripts/main/public/index.html
  src/scripts/main/public/js/dashboard.js
  src/scripts/main/public/js/feedback.js
  src/scripts/main/public/js/team_calendar.js
Labels: testing

#159 Theme switcher
  src/scripts/main/public/html/documentation.html
  src/scripts/main/public/index.html
  src/scripts/main/public/js/code-log.js
  src/scripts/main/public/js/dashboard.js
  src/scripts/main/public/js/task_script.js
  src/scripts/main/public/js/team_calendar.js
  src/scripts/main/public/js/themeswitch.js
  src/scripts/main/public/styles/main.css
  src/scripts/main/public/styles/task-list.css
  src/scripts/main/public/styles/team_calendar.css
Labels: css

#142 Finished comprehensive E2E testing for the entire site
  .github/workflows/main.yml
  __tests__/e2e/e2e.test.js
  __tests__/unit/team-calendar.test.js
  jest.setup.js
  src/scripts/main/public/html/add-list.html
  src/scripts/main/public/index.html
  src/scripts/main/public/js/task-script.js
  src/scripts/main/public/js/team-calendar.js
Labels: testing
